language: node_js
node_js:
- '8'
before_script:
- npm install --global @dhis2/deploy-build
script:
- npm run build
deploy:
- provider: script
  script: deploy-build
  skip_cleanup: true
  on:
    all_branches: true
- provider: script
  script: publish-build
  skip_cleanup: true
  on:
    tags: true
env:
  global:
    secure: UtA27JeFEdUmiZIiTwYUJosvdKtaZ7FwdpRUbf+cGYHypU6i4M5kAm0uUUXNUH6yc3RQ3dWDLgXWWRyU8KffOcOuXa65/peFPN0jQ6h+nzskd9pnM4V9FeRKo757XPftwYRDiu3Q/CUWfJd307mhPrS6Udb/bT/k+D1mUv06KAAYhBRPfBzN4A88MoMTF7hRRTR1p9O30D2bS7qbpRbRgxY19E3WQdNboVCI6X4IIDFSDRk1ZwsoZMxYW2i0boMJMoG2ce8RSC3M6KAhzSWJPDLzp9T0Wcgmfxdw/8F4bjADnsR28fIjiFU1QiodbRPtGjctjah8BSdBxtSyl5X/TRFpbtjxJuZ8eMwCAbdx9sBjkJ64H7Knu/9heRobwaifiDzDZ9E8IT+lOe41ifleeThJSkH7l0P45qDvwilE+x/bmS4BWjcSXFp4gNtR5HVfijnCtjNxg2VQnej2SNclF+5ODxZh53H7FcsT2GT/RrxVTWENkpT5DVJwgCySf6kcJyUI+uU+G5syXYF5aa3C7fmECHy5J3R0p99B6js9Y8AlBJjFOAJuxMaESf5bYS/ALu9CNnag6idHf/oGV5SQ3grHED07P6QAwooXX4G2rYwS2MZEAhhrn+lIP3Ccqf2o4DG/w+qFJ9YmjCF1vA3u8AB1TugyNcg1FEmtsgNJ9Kc=
notifications:
  slack:
    secure: i+G81ZMo0brh6cS3Z0+XQYSa51nPCctPMjuBhA5btQpTDppb3rwXlrjDzYg7NbWYinBC6EjAn5skwMogkof2k5yotjr3kFkGCER5HYR8aXf5xThC9rDTzkLRg+IaSVurYtILnh68AD/x36Qfm3gTVulB1fhGvtH4ohHa0bGcICo1QOdOd10uEGLT4pdDa8MhOjtcxAV9QAI/Wq3rcF1Ps51o+oIt9lBjqFZh84T0rDTapgV8Eh47rtj4la1kPhWMpGGGqaT/yVc+DgqLCuPc0CbRcchqbJcbAekUE70lVAZBrQ4tbGuSwn+99zXXLV0Tg8Ah92TXfcYibjt7uNdH/PE5SJ/wTWwZz4505kdnKoE6hWbF3Mk2ds5GmYgCLa4R77O8ONVP3YSdjgrNCrjSgQ5ivvbVw+B+p/wxvYJUp3RH/z/ntCowcLmguonWjSo3sIhBiLsM8s6L47A2J1oX3kXDRoKPuCPZj/Dgx1rhA7F39tbW/WCPhN8VKs4KIZaAiwxArPA0niOCym9skn9eZzh3lUvHk6dY/ZogIwBPzdss77mRwnLOCpx6e5tCRi8LpBpjQfnP3y7FL6hIso8b+9Bt9alpyP6bHruGa6wNRRBId1eVpHv2naC49Efth49ahUfue6McBrXj9ZhYRcZrXWHa+Dq+QhzkDZ+j0kyvzmI=
    on_success: change
    on_failure: always
